version: '3.8'
services:
  llm-slack-bot:
    image: hyun123/llm-slack-bot
    container_name: llm-slack-bot
    environment:
        ENV: 'dev'
    ports:
      - "5001:5001"
    volumes:
      - ".env:/opt/code/.env"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  tor_data:
