version: '3.8'
services:
  llm-slack-bot:
    image: hyun123/llm-slack-bot
    container_name: llm-slack-bot
    environment:
        ENV: 'dev'
    ports:
      - "5001:5001"
    volumes:
      - ".env:/opt/code/.env"
    # depends_on:
    #  - db # Removed as SQLite is used
    restart: unless-stopped
# db service removed as SQLite is used locally within the app service.
# The 'db_data' volume is no longer needed.
volumes:
  tor_data: # This volume seems unrelated to the db, keeping it
