version: '3.8'
services:
  tor:
    image: dperson/torproxy
    container_name: torproxy
    ports:
      - "9050:9050"
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    restart: unless-stopped
  llm-slack-bot:
    image: hyun123/llm-slack-bot
    container_name: llm-slack-bot
    ports:
      - "5001:5001"
    volumes:
      - ".env:/opt/code/.env"
      - tor_data:/etc/tor/run
    depends_on:
      - tor
    restart: unless-stopped
volumes:
  tor_data: