name: Build & Deploy (GHCR + Self-Hosted)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write   # GHCR push

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
  deploy:
    needs: build-push
    runs-on: [self-hosted, ec2]
    permissions:
      contents: read
      packages: read
    steps:
        - name: Pull & Up
          working-directory: /opt/app
          run: |
            docker compose pull
            docker compose up -d --remove-orphans